---
abstract: 'A GameState object for use with App::Betting::Toolkit'
author:
  - 'Paul G Webster <daemon@cpan.org>'
build_requires:
  ExtUtils::MakeMaker: 0
configure_requires:
  ExtUtils::MakeMaker: 0
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.64, CPAN::Meta::Converter version 2.120921'
license: bsd
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: App-Betting-Toolkit-GameState
no_index:
  directory:
    - t
    - inc
requires:
  Test::More: 0
version: 0.061
